### ISSUE TITLE
(require 'cl) deprecated in emacs 27

### ISSUE THREAD

**Issue by ericpmoss** [franzinc/eli#1]
Using emacs 27.x, I get warned that 'cl is a deprecated package.

I think the easy fix is to replace every occurrence of

  (require 'cl)

with:

(if (>= emacs-major-version 27)
    (require 'cl-lib)
  (require 'cl))

**Comment by OLDlayeratwork** [comment]
I have made the changes to use `cl-lib` from `cl`, but the changes are fairly extensive.  Changing things like `case` to `cl-case`, `loop` to `cl-loop`, `do` to `cl-do`, etc.  I expect the changes to appear in the `eli` repo in the next week.
